var allLangs = {
	'English' : 'en',
	'German' : 'de',
	'French' : 'fr',
	'Dutch' : 'nl',
	'Italian' : 'it',
	'Spanish' : 'es',
	'Russian' : 'ru',
	'Polish' : 'pl',
	'Japanese' : 'ja',
	'Portuguese' : 'pt',
	'Swedish' : 'sv',
	'Chinese' : 'zh',
	'Vietnamese' : 'vi',
	'Ukrainian' : 'uk',
	'Catalan' : 'ca',
	'Norwegian Bokml' : 'no',
	'Finnish' : 'fi',
	'Persian' : 'fa',
	'Czech' : 'cs',
	'Hungarian' : 'hu',
	'Korean' : 'ko',
	'Romanian' : 'ro',
	'Indonesian' : 'id',
	'Arabic' : 'ar',
	'Turkish' : 'tr',
	'Kazakh' : 'kk',
	'Slovak' : 'sk',
	'Serbian' : 'sr',
	'Malay' : 'ms',
	'Esperanto' : 'eo',
	'Danish' : 'da',
	'Lithuanian' : 'lt',
	'Basque' : 'eu',
	'Bulgarian' : 'bg',
	'Hebrew' : 'he',
	'Slovenian' : 'sl',
	'Croatian' : 'hr',
	'Volapk' : 'vo',
	'WarayWaray' : 'war',
	'Estonian' : 'et',
	'Hindi' : 'hi',
	'Cebuano' : 'ceb',
	'Galician' : 'gl',
	'Norwegian Nynorsk' : 'nn',
	'Simple English' : 'simple',
	'Azerbaijani' : 'az',
	'Latin' : 'la',
	'Greek' : 'el',
	'Uzbek' : 'uz',
	'Thai' : 'th',
	'SerboCroatian' : 'sh',
	'Occitan' : 'oc'
};